#!/bin/bash

# Installing Juxl extension
echo "Installing Juxl Feedback extension..."
pip install juxl_extension-3.4.1-py3-none-any.whl
 
# Installing Juxl Logging extension
echo "Installing Juxl Logging Feedback extension..."
pip install juxl_logging-3.2.0-py3-none-any.whl

# Copying overrides.json to the appropriate location
echo "Copying JupyterLab settings overrides..."
mkdir -p /srv/conda/envs/notebook/share/jupyter/lab/settings/
cp overrides.json /srv/conda/envs/notebook/share/jupyter/lab/settings/overrides.json

# Updating Jupyter Notebook configuration
echo "Updating Jupyter Notebook configuration..."
mkdir -p ~/.jupyter/
echo "c.NotebookApp.allow_origin = 'https://juxlauth-codingai.elearn.rwth-aachen.de'" > ~/.jupyter/jupyter_notebook_config.py

# Installing JupyterLab Feedback extension
echo "Installing JupyterLab Feedback extension..."
pip install jupyterlab_feedback-0.6.2-py3-none-any.whl

# Verifying installed JupyterLab extensions
echo "Verifying JupyterLab extensions..."
jupyter labextension list
