#!/bin/bash

# Define variables for paths
SETTINGS_DIR=$(jupyter --data-dir)/lab/settings/

# Installing Juxl extensions
echo "Installing Juxl extensions..."
jupyter labextension install @juxl/juxl-extension@^3.1.1 2>&1 | tee juxl-extension.log
jupyter labextension install @juxl/logging@^3.1.1 2>&1 | tee juxl-logging.log

# Building JupyterLab
echo "Building JupyterLab..."
jupyter lab build 2>&1 | tee jupyter-build.log

# Copying overrides.json to the appropriate location
echo "Copying JupyterLab settings overrides..."
mkdir -p $SETTINGS_DIR
cp overrides.json $SETTINGS_DIR/overrides.json

# Updating Jupyter Notebook configuration
echo "Updating Jupyter Notebook configuration..."
mkdir -p ~/.jupyter/
echo "c.NotebookApp.allow_origin = 'https://juxlauth-codingai.elearn.rwth-aachen.de'" > ~/.jupyter/jupyter_notebook_config.py

# Installing JupyterLab Feedback extension
echo "Installing JupyterLab Feedback extension..."
pip install jupyterlab_feedback-0.6.2-py3-none-any.whl 2>&1 | tee feedback-install.log

# Verifying installed JupyterLab extensions
echo "Verifying JupyterLab extensions..."
jupyter labextension list 2>&1 | tee extension-list.log
